quadrantChart
    title Reach and engagement of CLI card games
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Python Snake Game": [0.3, 0.6]
    "CLI Poker Game": [0.45, 0.23]
    "CLI Casino Games": [0.57, 0.69]
    "CLI Card Games": [0.78, 0.34]
    "CLI Casino Simulator": [0.40, 0.34]
    "CLI Casino Blackjack": [0.35, 0.78]
    "CLI Card Game Suite": [0.5, 0.6]
    "Our Target Product": [0.6, 0.7]
