quadrantChart
    title Reach and engagement of AWS EC2 instance creation tools
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "AWS Management Console": [0.8, 0.9]
    "Terraform": [0.6, 0.7]
    "Google Cloud Platform": [0.7, 0.8]
    "Microsoft Azure": [0.7, 0.8]
    "DigitalOcean": [0.5, 0.6]
    "Vultr": [0.4, 0.5]
    "Linode": [0.5, 0.6]
    "Our Target Product": [0.6, 0.7]
